// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: newsletter/newsletter/newsletters_basic.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NewslettersBasic struct {
	Title           string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SubscriberCount uint64 `protobuf:"varint,2,opt,name=subscriberCount,proto3" json:"subscriberCount,omitempty"`
}

func (m *NewslettersBasic) Reset()         { *m = NewslettersBasic{} }
func (m *NewslettersBasic) String() string { return proto.CompactTextString(m) }
func (*NewslettersBasic) ProtoMessage()    {}
func (*NewslettersBasic) Descriptor() ([]byte, []int) {
	return fileDescriptor_4089d37c3086eea5, []int{0}
}
func (m *NewslettersBasic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NewslettersBasic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NewslettersBasic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NewslettersBasic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewslettersBasic.Merge(m, src)
}
func (m *NewslettersBasic) XXX_Size() int {
	return m.Size()
}
func (m *NewslettersBasic) XXX_DiscardUnknown() {
	xxx_messageInfo_NewslettersBasic.DiscardUnknown(m)
}

var xxx_messageInfo_NewslettersBasic proto.InternalMessageInfo

func (m *NewslettersBasic) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewslettersBasic) GetSubscriberCount() uint64 {
	if m != nil {
		return m.SubscriberCount
	}
	return 0
}

func init() {
	proto.RegisterType((*NewslettersBasic)(nil), "newsletter.newsletter.NewslettersBasic")
}

func init() {
	proto.RegisterFile("newsletter/newsletter/newsletters_basic.proto", fileDescriptor_4089d37c3086eea5)
}

var fileDescriptor_4089d37c3086eea5 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcd, 0x4b, 0x2d, 0x2f,
	0xce, 0x49, 0x2d, 0x29, 0x49, 0x2d, 0xd2, 0xc7, 0xca, 0x2c, 0x8e, 0x4f, 0x4a, 0x2c, 0xce, 0x4c,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x45, 0x48, 0xe8, 0x21, 0x98, 0x4a, 0x41, 0x5c,
	0x02, 0x7e, 0x08, 0x1d, 0x4e, 0x20, 0x0d, 0x42, 0x22, 0x5c, 0xac, 0x25, 0x99, 0x25, 0x39, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x06, 0x17, 0x7f, 0x71, 0x69, 0x52,
	0x71, 0x72, 0x51, 0x66, 0x52, 0x6a, 0x91, 0x73, 0x7e, 0x69, 0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0x4b, 0x10, 0xba, 0xb0, 0x93, 0xf9, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e,
	0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31,
	0x44, 0xc9, 0x22, 0x39, 0xb4, 0x02, 0xd9, 0xd5, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0x60,
	0xa7, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0x6b, 0x35, 0x9f, 0xdb, 0x00, 0x00, 0x00,
}

func (m *NewslettersBasic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewslettersBasic) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NewslettersBasic) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubscriberCount != 0 {
		i = encodeVarintNewslettersBasic(dAtA, i, uint64(m.SubscriberCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintNewslettersBasic(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNewslettersBasic(dAtA []byte, offset int, v uint64) int {
	offset -= sovNewslettersBasic(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NewslettersBasic) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovNewslettersBasic(uint64(l))
	}
	if m.SubscriberCount != 0 {
		n += 1 + sovNewslettersBasic(uint64(m.SubscriberCount))
	}
	return n
}

func sovNewslettersBasic(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNewslettersBasic(x uint64) (n int) {
	return sovNewslettersBasic(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NewslettersBasic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNewslettersBasic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewslettersBasic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewslettersBasic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNewslettersBasic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNewslettersBasic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNewslettersBasic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriberCount", wireType)
			}
			m.SubscriberCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNewslettersBasic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriberCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNewslettersBasic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNewslettersBasic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNewslettersBasic(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNewslettersBasic
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNewslettersBasic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNewslettersBasic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNewslettersBasic
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNewslettersBasic
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNewslettersBasic
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNewslettersBasic        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNewslettersBasic          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNewslettersBasic = fmt.Errorf("proto: unexpected end of group")
)
