// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: newsletter/newsletter/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetNewsletterInfoRequest struct {
}

func (m *QueryGetNewsletterInfoRequest) Reset()         { *m = QueryGetNewsletterInfoRequest{} }
func (m *QueryGetNewsletterInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNewsletterInfoRequest) ProtoMessage()    {}
func (*QueryGetNewsletterInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{2}
}
func (m *QueryGetNewsletterInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNewsletterInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNewsletterInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNewsletterInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNewsletterInfoRequest.Merge(m, src)
}
func (m *QueryGetNewsletterInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNewsletterInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNewsletterInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNewsletterInfoRequest proto.InternalMessageInfo

type QueryGetNewsletterInfoResponse struct {
	NewsletterInfo NewsletterInfo `protobuf:"bytes,1,opt,name=NewsletterInfo,proto3" json:"NewsletterInfo"`
}

func (m *QueryGetNewsletterInfoResponse) Reset()         { *m = QueryGetNewsletterInfoResponse{} }
func (m *QueryGetNewsletterInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNewsletterInfoResponse) ProtoMessage()    {}
func (*QueryGetNewsletterInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{3}
}
func (m *QueryGetNewsletterInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNewsletterInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNewsletterInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNewsletterInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNewsletterInfoResponse.Merge(m, src)
}
func (m *QueryGetNewsletterInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNewsletterInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNewsletterInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNewsletterInfoResponse proto.InternalMessageInfo

func (m *QueryGetNewsletterInfoResponse) GetNewsletterInfo() NewsletterInfo {
	if m != nil {
		return m.NewsletterInfo
	}
	return NewsletterInfo{}
}

type QueryGetNewsletterRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetNewsletterRequest) Reset()         { *m = QueryGetNewsletterRequest{} }
func (m *QueryGetNewsletterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNewsletterRequest) ProtoMessage()    {}
func (*QueryGetNewsletterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{4}
}
func (m *QueryGetNewsletterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNewsletterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNewsletterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNewsletterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNewsletterRequest.Merge(m, src)
}
func (m *QueryGetNewsletterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNewsletterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNewsletterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNewsletterRequest proto.InternalMessageInfo

func (m *QueryGetNewsletterRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetNewsletterResponse struct {
	Newsletter Newsletter `protobuf:"bytes,1,opt,name=newsletter,proto3" json:"newsletter"`
}

func (m *QueryGetNewsletterResponse) Reset()         { *m = QueryGetNewsletterResponse{} }
func (m *QueryGetNewsletterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNewsletterResponse) ProtoMessage()    {}
func (*QueryGetNewsletterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{5}
}
func (m *QueryGetNewsletterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNewsletterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNewsletterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNewsletterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNewsletterResponse.Merge(m, src)
}
func (m *QueryGetNewsletterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNewsletterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNewsletterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNewsletterResponse proto.InternalMessageInfo

func (m *QueryGetNewsletterResponse) GetNewsletter() Newsletter {
	if m != nil {
		return m.Newsletter
	}
	return Newsletter{}
}

type QueryAllNewsletterRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNewsletterRequest) Reset()         { *m = QueryAllNewsletterRequest{} }
func (m *QueryAllNewsletterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNewsletterRequest) ProtoMessage()    {}
func (*QueryAllNewsletterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{6}
}
func (m *QueryAllNewsletterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNewsletterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNewsletterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNewsletterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNewsletterRequest.Merge(m, src)
}
func (m *QueryAllNewsletterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNewsletterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNewsletterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNewsletterRequest proto.InternalMessageInfo

func (m *QueryAllNewsletterRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllNewsletterResponse struct {
	Newsletter []Newsletter        `protobuf:"bytes,1,rep,name=newsletter,proto3" json:"newsletter"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNewsletterResponse) Reset()         { *m = QueryAllNewsletterResponse{} }
func (m *QueryAllNewsletterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNewsletterResponse) ProtoMessage()    {}
func (*QueryAllNewsletterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{7}
}
func (m *QueryAllNewsletterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNewsletterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNewsletterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNewsletterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNewsletterResponse.Merge(m, src)
}
func (m *QueryAllNewsletterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNewsletterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNewsletterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNewsletterResponse proto.InternalMessageInfo

func (m *QueryAllNewsletterResponse) GetNewsletter() []Newsletter {
	if m != nil {
		return m.Newsletter
	}
	return nil
}

func (m *QueryAllNewsletterResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryNewslettersBasicRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryNewslettersBasicRequest) Reset()         { *m = QueryNewslettersBasicRequest{} }
func (m *QueryNewslettersBasicRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNewslettersBasicRequest) ProtoMessage()    {}
func (*QueryNewslettersBasicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{8}
}
func (m *QueryNewslettersBasicRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNewslettersBasicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNewslettersBasicRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNewslettersBasicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNewslettersBasicRequest.Merge(m, src)
}
func (m *QueryNewslettersBasicRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNewslettersBasicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNewslettersBasicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNewslettersBasicRequest proto.InternalMessageInfo

func (m *QueryNewslettersBasicRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryNewslettersBasicResponse struct {
	Newsletters []NewslettersBasic  `protobuf:"bytes,1,rep,name=newsletters,proto3" json:"newsletters"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryNewslettersBasicResponse) Reset()         { *m = QueryNewslettersBasicResponse{} }
func (m *QueryNewslettersBasicResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNewslettersBasicResponse) ProtoMessage()    {}
func (*QueryNewslettersBasicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{9}
}
func (m *QueryNewslettersBasicResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNewslettersBasicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNewslettersBasicResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNewslettersBasicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNewslettersBasicResponse.Merge(m, src)
}
func (m *QueryNewslettersBasicResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNewslettersBasicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNewslettersBasicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNewslettersBasicResponse proto.InternalMessageInfo

func (m *QueryNewslettersBasicResponse) GetNewsletters() []NewslettersBasic {
	if m != nil {
		return m.Newsletters
	}
	return nil
}

func (m *QueryNewslettersBasicResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryNewslettersByTitleRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Title      string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (m *QueryNewslettersByTitleRequest) Reset()         { *m = QueryNewslettersByTitleRequest{} }
func (m *QueryNewslettersByTitleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNewslettersByTitleRequest) ProtoMessage()    {}
func (*QueryNewslettersByTitleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{10}
}
func (m *QueryNewslettersByTitleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNewslettersByTitleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNewslettersByTitleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNewslettersByTitleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNewslettersByTitleRequest.Merge(m, src)
}
func (m *QueryNewslettersByTitleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNewslettersByTitleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNewslettersByTitleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNewslettersByTitleRequest proto.InternalMessageInfo

func (m *QueryNewslettersByTitleRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryNewslettersByTitleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type QueryNewslettersByTitleResponse struct {
	Newsletter Newsletter `protobuf:"bytes,1,opt,name=newsletter,proto3" json:"newsletter"`
}

func (m *QueryNewslettersByTitleResponse) Reset()         { *m = QueryNewslettersByTitleResponse{} }
func (m *QueryNewslettersByTitleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNewslettersByTitleResponse) ProtoMessage()    {}
func (*QueryNewslettersByTitleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_304ab6b705737e70, []int{11}
}
func (m *QueryNewslettersByTitleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNewslettersByTitleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNewslettersByTitleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNewslettersByTitleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNewslettersByTitleResponse.Merge(m, src)
}
func (m *QueryNewslettersByTitleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNewslettersByTitleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNewslettersByTitleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNewslettersByTitleResponse proto.InternalMessageInfo

func (m *QueryNewslettersByTitleResponse) GetNewsletter() Newsletter {
	if m != nil {
		return m.Newsletter
	}
	return Newsletter{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "newsletter.newsletter.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "newsletter.newsletter.QueryParamsResponse")
	proto.RegisterType((*QueryGetNewsletterInfoRequest)(nil), "newsletter.newsletter.QueryGetNewsletterInfoRequest")
	proto.RegisterType((*QueryGetNewsletterInfoResponse)(nil), "newsletter.newsletter.QueryGetNewsletterInfoResponse")
	proto.RegisterType((*QueryGetNewsletterRequest)(nil), "newsletter.newsletter.QueryGetNewsletterRequest")
	proto.RegisterType((*QueryGetNewsletterResponse)(nil), "newsletter.newsletter.QueryGetNewsletterResponse")
	proto.RegisterType((*QueryAllNewsletterRequest)(nil), "newsletter.newsletter.QueryAllNewsletterRequest")
	proto.RegisterType((*QueryAllNewsletterResponse)(nil), "newsletter.newsletter.QueryAllNewsletterResponse")
	proto.RegisterType((*QueryNewslettersBasicRequest)(nil), "newsletter.newsletter.QueryNewslettersBasicRequest")
	proto.RegisterType((*QueryNewslettersBasicResponse)(nil), "newsletter.newsletter.QueryNewslettersBasicResponse")
	proto.RegisterType((*QueryNewslettersByTitleRequest)(nil), "newsletter.newsletter.QueryNewslettersByTitleRequest")
	proto.RegisterType((*QueryNewslettersByTitleResponse)(nil), "newsletter.newsletter.QueryNewslettersByTitleResponse")
}

func init() { proto.RegisterFile("newsletter/newsletter/query.proto", fileDescriptor_304ab6b705737e70) }

var fileDescriptor_304ab6b705737e70 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x85, 0x16, 0xf5, 0x55, 0x20, 0x74, 0x14, 0x09, 0xac, 0xc6, 0xa1, 0x46, 0xfd,
	0xad, 0xda, 0x4d, 0x7f, 0xc0, 0xc0, 0xd4, 0x0e, 0x54, 0x2c, 0x50, 0x02, 0x13, 0x4b, 0xe5, 0x94,
	0xab, 0x65, 0xe4, 0xfa, 0xdc, 0x9c, 0x0b, 0x8d, 0x10, 0x0c, 0x0c, 0xcc, 0x48, 0xfc, 0x01, 0x2c,
	0xac, 0xc0, 0x0a, 0xff, 0x41, 0xc7, 0x4a, 0x2c, 0x4c, 0x08, 0x35, 0xfc, 0x0d, 0xcc, 0xc8, 0x77,
	0x2f, 0xd8, 0x49, 0xec, 0xd8, 0x41, 0xd9, 0x2e, 0xf6, 0xf7, 0xbd, 0xef, 0xe7, 0x9e, 0xde, 0x7b,
	0x31, 0x4c, 0xfb, 0xec, 0x85, 0xf0, 0x58, 0x18, 0xb2, 0x86, 0x95, 0x38, 0x1e, 0x1e, 0xb1, 0x46,
	0xd3, 0x0c, 0x1a, 0x3c, 0xe4, 0xf4, 0x6a, 0xfc, 0xdc, 0x8c, 0x8f, 0xda, 0xa4, 0xc3, 0x1d, 0x2e,
	0x15, 0x56, 0x74, 0x52, 0x62, 0x6d, 0xca, 0xe1, 0xdc, 0xf1, 0x98, 0x65, 0x07, 0xae, 0x65, 0xfb,
	0x3e, 0x0f, 0xed, 0xd0, 0xe5, 0xbe, 0xc0, 0xb7, 0x8b, 0x7b, 0x5c, 0x1c, 0x70, 0x61, 0xd5, 0x6d,
	0xc1, 0x94, 0x87, 0xf5, 0xbc, 0x5a, 0x67, 0xa1, 0x5d, 0xb5, 0x02, 0xdb, 0x71, 0x7d, 0x29, 0x46,
	0xad, 0x91, 0x4e, 0x16, 0xd8, 0x0d, 0xfb, 0xa0, 0x9d, 0x6f, 0x29, 0x5d, 0x13, 0x1f, 0x77, 0x5d,
	0x7f, 0xbf, 0x8d, 0x36, 0x9b, 0x27, 0x46, 0xdd, 0x72, 0x9e, 0x4e, 0xec, 0xd6, 0x6d, 0xe1, 0xee,
	0x29, 0xb9, 0x31, 0x09, 0xf4, 0x61, 0x74, 0x93, 0x1d, 0x09, 0x56, 0x63, 0x87, 0x47, 0x4c, 0x84,
	0x46, 0x0d, 0xae, 0x74, 0x3c, 0x15, 0x01, 0xf7, 0x05, 0xa3, 0x77, 0x60, 0x4c, 0x5d, 0xe0, 0x1a,
	0xb9, 0x41, 0xe6, 0x27, 0x56, 0xcb, 0x66, 0x6a, 0x71, 0x4d, 0x15, 0xb6, 0x75, 0xfe, 0xe4, 0x67,
	0xa5, 0x54, 0xc3, 0x10, 0xa3, 0x02, 0x65, 0x99, 0x73, 0x9b, 0x85, 0xf7, 0xff, 0x49, 0xef, 0xf9,
	0xfb, 0xbc, 0x6d, 0x7a, 0x04, 0x7a, 0x96, 0x00, 0xfd, 0x1f, 0xc1, 0xa5, 0xce, 0x37, 0xc8, 0x31,
	0x93, 0xc1, 0xd1, 0x29, 0x46, 0x9e, 0xae, 0x14, 0x46, 0x15, 0xae, 0xf7, 0xda, 0x22, 0x13, 0x9d,
	0x84, 0x51, 0xd7, 0x7f, 0xca, 0x8e, 0xa5, 0xd1, 0x78, 0x4d, 0xfd, 0x30, 0x18, 0x68, 0x69, 0x21,
	0x48, 0xb9, 0x0d, 0x10, 0x33, 0x20, 0xe1, 0x74, 0x2e, 0x21, 0xd2, 0x25, 0x42, 0x8d, 0x3d, 0x24,
	0xdb, 0xf4, 0xbc, 0x5e, 0xb2, 0xbb, 0x00, 0x71, 0xd3, 0xa1, 0xcb, 0xac, 0xa9, 0x3a, 0xd4, 0x8c,
	0x3a, 0xd4, 0x54, 0x53, 0x80, 0x1d, 0x6a, 0xee, 0xd8, 0x0e, 0xc3, 0xd8, 0x5a, 0x22, 0xd2, 0xf8,
	0x4c, 0xf0, 0x32, 0x5d, 0x2e, 0x19, 0x97, 0x39, 0xf7, 0x9f, 0x97, 0x89, 0x12, 0x25, 0x78, 0x47,
	0x24, 0xef, 0x5c, 0x2e, 0xaf, 0xa2, 0xe8, 0x00, 0xde, 0x87, 0x29, 0xc9, 0x1b, 0xbb, 0x89, 0xad,
	0xa8, 0xa1, 0x87, 0x5d, 0x98, 0x6f, 0x04, 0x1b, 0xb6, 0xd7, 0x08, 0x6b, 0xf3, 0x00, 0x26, 0x12,
	0x63, 0x85, 0xc5, 0x99, 0xcb, 0x2d, 0x8e, 0xca, 0x82, 0x25, 0x4a, 0x66, 0x18, 0x5e, 0x8d, 0x5e,
	0xe3, 0x28, 0x25, 0x4d, 0x9b, 0x8f, 0xdd, 0xd0, 0x63, 0x43, 0xae, 0x52, 0x34, 0x20, 0x61, 0x94,
	0x57, 0xd2, 0x8e, 0xd7, 0xd4, 0x0f, 0xe3, 0x19, 0x54, 0x32, 0xfd, 0x87, 0x3c, 0x25, 0xab, 0x7f,
	0x2e, 0xc0, 0xa8, 0x34, 0xa3, 0x6f, 0x09, 0x8c, 0xa9, 0xd5, 0x43, 0x17, 0x32, 0x32, 0xf5, 0xee,
	0x3a, 0x6d, 0xb1, 0x88, 0x54, 0x41, 0x1b, 0x33, 0x6f, 0xbe, 0xff, 0x7e, 0x3f, 0x52, 0xa1, 0x65,
	0xab, 0xdf, 0x7a, 0xa7, 0x9f, 0x48, 0xf7, 0xa2, 0xa2, 0xeb, 0xfd, 0x5c, 0xb2, 0x56, 0xa2, 0xb6,
	0x31, 0x60, 0x14, 0x62, 0x9a, 0x12, 0x73, 0x9e, 0xce, 0x5a, 0x85, 0xfe, 0x61, 0xe8, 0x47, 0x02,
	0x10, 0xa7, 0xa2, 0x2b, 0x85, 0x5d, 0xdb, 0x9c, 0xd5, 0x01, 0x22, 0x90, 0xb1, 0x2a, 0x19, 0x97,
	0xe8, 0x42, 0x2e, 0xa3, 0xf5, 0x52, 0x6e, 0xdd, 0x57, 0xf4, 0x03, 0x81, 0x8b, 0x71, 0xa6, 0x4d,
	0xcf, 0xeb, 0x4f, 0x9a, 0xb6, 0x36, 0xfb, 0x93, 0xa6, 0xae, 0x40, 0x63, 0x41, 0x92, 0xde, 0xa4,
	0xd3, 0xb9, 0xa4, 0xf4, 0x0b, 0x81, 0xcb, 0xdd, 0x83, 0x4e, 0xd7, 0xfa, 0x59, 0x66, 0x6c, 0x31,
	0x6d, 0x7d, 0xb0, 0x20, 0x44, 0x5d, 0x91, 0xa8, 0x8b, 0x74, 0xde, 0x2a, 0xf8, 0x15, 0x40, 0xbf,
	0x12, 0xa0, 0xbd, 0x53, 0x4a, 0x37, 0x8a, 0xda, 0x77, 0x6c, 0x15, 0xed, 0xd6, 0xa0, 0x61, 0xc8,
	0xbd, 0x26, 0xb9, 0x97, 0xe9, 0x52, 0x11, 0xee, 0xe6, 0xae, 0x5c, 0x32, 0x5b, 0xb7, 0x4f, 0xce,
	0x74, 0x72, 0x7a, 0xa6, 0x93, 0x5f, 0x67, 0x3a, 0x79, 0xd7, 0xd2, 0x4b, 0xa7, 0x2d, 0xbd, 0xf4,
	0xa3, 0xa5, 0x97, 0x9e, 0x94, 0x13, 0xa1, 0xc7, 0xc9, 0x3c, 0x61, 0x33, 0x60, 0xa2, 0x3e, 0x26,
	0x3f, 0x7d, 0xd6, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x76, 0xad, 0x49, 0x3e, 0x0a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a NewsletterInfo by index.
	NewsletterInfo(ctx context.Context, in *QueryGetNewsletterInfoRequest, opts ...grpc.CallOption) (*QueryGetNewsletterInfoResponse, error)
	// Queries a list of Newsletter items.
	Newsletter(ctx context.Context, in *QueryGetNewsletterRequest, opts ...grpc.CallOption) (*QueryGetNewsletterResponse, error)
	NewsletterAll(ctx context.Context, in *QueryAllNewsletterRequest, opts ...grpc.CallOption) (*QueryAllNewsletterResponse, error)
	// Queries a list of NewslettersBasic items.
	NewslettersBasic(ctx context.Context, in *QueryNewslettersBasicRequest, opts ...grpc.CallOption) (*QueryNewslettersBasicResponse, error)
	// Queries a list of NewslettersByTitle items.
	NewslettersByTitle(ctx context.Context, in *QueryNewslettersByTitleRequest, opts ...grpc.CallOption) (*QueryNewslettersByTitleResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/newsletter.newsletter.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewsletterInfo(ctx context.Context, in *QueryGetNewsletterInfoRequest, opts ...grpc.CallOption) (*QueryGetNewsletterInfoResponse, error) {
	out := new(QueryGetNewsletterInfoResponse)
	err := c.cc.Invoke(ctx, "/newsletter.newsletter.Query/NewsletterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Newsletter(ctx context.Context, in *QueryGetNewsletterRequest, opts ...grpc.CallOption) (*QueryGetNewsletterResponse, error) {
	out := new(QueryGetNewsletterResponse)
	err := c.cc.Invoke(ctx, "/newsletter.newsletter.Query/Newsletter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewsletterAll(ctx context.Context, in *QueryAllNewsletterRequest, opts ...grpc.CallOption) (*QueryAllNewsletterResponse, error) {
	out := new(QueryAllNewsletterResponse)
	err := c.cc.Invoke(ctx, "/newsletter.newsletter.Query/NewsletterAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewslettersBasic(ctx context.Context, in *QueryNewslettersBasicRequest, opts ...grpc.CallOption) (*QueryNewslettersBasicResponse, error) {
	out := new(QueryNewslettersBasicResponse)
	err := c.cc.Invoke(ctx, "/newsletter.newsletter.Query/NewslettersBasic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewslettersByTitle(ctx context.Context, in *QueryNewslettersByTitleRequest, opts ...grpc.CallOption) (*QueryNewslettersByTitleResponse, error) {
	out := new(QueryNewslettersByTitleResponse)
	err := c.cc.Invoke(ctx, "/newsletter.newsletter.Query/NewslettersByTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a NewsletterInfo by index.
	NewsletterInfo(context.Context, *QueryGetNewsletterInfoRequest) (*QueryGetNewsletterInfoResponse, error)
	// Queries a list of Newsletter items.
	Newsletter(context.Context, *QueryGetNewsletterRequest) (*QueryGetNewsletterResponse, error)
	NewsletterAll(context.Context, *QueryAllNewsletterRequest) (*QueryAllNewsletterResponse, error)
	// Queries a list of NewslettersBasic items.
	NewslettersBasic(context.Context, *QueryNewslettersBasicRequest) (*QueryNewslettersBasicResponse, error)
	// Queries a list of NewslettersByTitle items.
	NewslettersByTitle(context.Context, *QueryNewslettersByTitleRequest) (*QueryNewslettersByTitleResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) NewsletterInfo(ctx context.Context, req *QueryGetNewsletterInfoRequest) (*QueryGetNewsletterInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewsletterInfo not implemented")
}
func (*UnimplementedQueryServer) Newsletter(ctx context.Context, req *QueryGetNewsletterRequest) (*QueryGetNewsletterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Newsletter not implemented")
}
func (*UnimplementedQueryServer) NewsletterAll(ctx context.Context, req *QueryAllNewsletterRequest) (*QueryAllNewsletterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewsletterAll not implemented")
}
func (*UnimplementedQueryServer) NewslettersBasic(ctx context.Context, req *QueryNewslettersBasicRequest) (*QueryNewslettersBasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewslettersBasic not implemented")
}
func (*UnimplementedQueryServer) NewslettersByTitle(ctx context.Context, req *QueryNewslettersByTitleRequest) (*QueryNewslettersByTitleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewslettersByTitle not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsletter.newsletter.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewsletterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNewsletterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewsletterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsletter.newsletter.Query/NewsletterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewsletterInfo(ctx, req.(*QueryGetNewsletterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Newsletter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNewsletterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Newsletter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsletter.newsletter.Query/Newsletter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Newsletter(ctx, req.(*QueryGetNewsletterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewsletterAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNewsletterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewsletterAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsletter.newsletter.Query/NewsletterAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewsletterAll(ctx, req.(*QueryAllNewsletterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewslettersBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNewslettersBasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewslettersBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsletter.newsletter.Query/NewslettersBasic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewslettersBasic(ctx, req.(*QueryNewslettersBasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewslettersByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNewslettersByTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewslettersByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsletter.newsletter.Query/NewslettersByTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewslettersByTitle(ctx, req.(*QueryNewslettersByTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "newsletter.newsletter.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "NewsletterInfo",
			Handler:    _Query_NewsletterInfo_Handler,
		},
		{
			MethodName: "Newsletter",
			Handler:    _Query_Newsletter_Handler,
		},
		{
			MethodName: "NewsletterAll",
			Handler:    _Query_NewsletterAll_Handler,
		},
		{
			MethodName: "NewslettersBasic",
			Handler:    _Query_NewslettersBasic_Handler,
		},
		{
			MethodName: "NewslettersByTitle",
			Handler:    _Query_NewslettersByTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "newsletter/newsletter/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNewsletterInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNewsletterInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNewsletterInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetNewsletterInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNewsletterInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNewsletterInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NewsletterInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNewsletterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNewsletterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNewsletterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNewsletterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNewsletterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNewsletterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Newsletter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllNewsletterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNewsletterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNewsletterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNewsletterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNewsletterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNewsletterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Newsletter) > 0 {
		for iNdEx := len(m.Newsletter) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Newsletter[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryNewslettersBasicRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNewslettersBasicRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNewslettersBasicRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNewslettersBasicResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNewslettersBasicResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNewslettersBasicResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Newsletters) > 0 {
		for iNdEx := len(m.Newsletters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Newsletters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryNewslettersByTitleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNewslettersByTitleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNewslettersByTitleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNewslettersByTitleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNewslettersByTitleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNewslettersByTitleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Newsletter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNewsletterInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetNewsletterInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NewsletterInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNewsletterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNewsletterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Newsletter.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllNewsletterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNewsletterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Newsletter) > 0 {
		for _, e := range m.Newsletter {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNewslettersBasicRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNewslettersBasicResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Newsletters) > 0 {
		for _, e := range m.Newsletters {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNewslettersByTitleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNewslettersByTitleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Newsletter.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNewsletterInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNewsletterInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNewsletterInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNewsletterInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNewsletterInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNewsletterInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewsletterInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewsletterInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNewsletterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNewsletterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNewsletterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNewsletterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNewsletterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNewsletterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Newsletter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Newsletter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNewsletterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNewsletterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNewsletterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNewsletterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNewsletterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNewsletterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Newsletter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Newsletter = append(m.Newsletter, Newsletter{})
			if err := m.Newsletter[len(m.Newsletter)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNewslettersBasicRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNewslettersBasicRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNewslettersBasicRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNewslettersBasicResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNewslettersBasicResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNewslettersBasicResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Newsletters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Newsletters = append(m.Newsletters, NewslettersBasic{})
			if err := m.Newsletters[len(m.Newsletters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNewslettersByTitleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNewslettersByTitleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNewslettersByTitleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNewslettersByTitleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNewslettersByTitleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNewslettersByTitleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Newsletter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Newsletter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
